apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-evaluation-service-config
  labels:
    app: evaluation-service
    release: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
