name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.base
          push: true
          tags: hudamawood/rag-base:latest,hudamawood/rag-base:${{ github.sha }}
          cache-from: type=registry,ref=hudamawood/rag-base:latest
          cache-to: type=inline

      - name: Build and Push Monolith Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.monolith
          push: true
          tags: hudamawood/rag-monolith:latest,hudamawood/rag-monolith:${{ github.sha }}
          cache-from: type=registry,ref=hudamawood/rag-monolith:latest
          cache-to: type=inline

      - name: Build and Push Worker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.worker
          push: true
          tags: hudamawood/rag-worker:latest,hudamawood/rag-worker:${{ github.sha }}
          cache-from: type=registry,ref=hudamawood/rag-worker:latest
          cache-to: type=inline

      - name: Build and Push Evaluation Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.evaluation
          push: true
          tags: hudamawood/rag-evaluation:latest,hudamawood/rag-evaluation:${{ github.sha }}
          cache-from: type=registry,ref=hudamawood/rag-evaluation:latest
          cache-to: type=inline

      - name: Build and Push UI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.rag-ui
          push: true
          tags: hudamawood/rag-ui:latest,hudamawood/rag-ui:${{ github.sha }}
          cache-from: type=registry,ref=hudamawood/rag-ui:latest
          cache-to: type=inline
